language: android

jdk:
  - oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-27
    - extra-google-m2repository

notifications:
  email: false

sudo: false

before_script: 
    - chmod +x gradlew
